# Generated by Django 4.2.6 on 2023-10-08 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_author', models.CharField(max_length=50, null=True)),
                ('content', models.TextField()),
                ('pub_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('user_author__isnull', True), ('guest_author__isnull', False)), models.Q(('user_author__isnull', False), ('guest_author__isnull', True)), _connector='OR'), name='only_one_author_type'),
        ),
    ]
