# Generated by Django 4.2.6 on 2023-10-06 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGithubInfo',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='github_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('handle', models.CharField(max_length=39)),
            ],
        ),
    ]
