# Generated by Django 4.2.6 on 2023-10-16 18:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clickergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allowed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
